### ISSUE TITLE
Package via pip is Out of Date/Broken for Python 3

### ISSUE THREAD

**Issue by mriveralee** [nebstrebor/django-shortuuidfield#6]
The python package available on via `pip install django-shortuuidfield` is an old version that is broken for python3. (Specifically all commits after and including the [updated raised exception handling](https://github.com/nebstrebor/django-shortuuidfield/commit/5493f78cd9225dc4a46689f09f75af59dfea9e16) aren't reflected in the package.

```
   from shortuuidfield import ShortUUIDField
  File "/.../python3.4/site-packages/shortuuidfield/__init__.py", line 4
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

Steps to Repro: 
1) `pip install django-shortuuidfield` (https://pypi.python.org/pypi/django-shortuuidfield/0.1.2)
2) Try to use the package on django + python3

**Comment by nebstrebor** [comment]
Thanks for the heads up . I'll try to get the pip version updated right away.

**Comment by nebstrebor** [comment]
@mriveralee sorry it took a few days to get around to this, if you can fork to make it py3 compatible and submit a pull request, I'll pull it in and get the pypi file updated.  I noticed there is an [older pull request](https://github.com/nebstrebor/django-shortuuidfield/pull/3) but it has conflicts so i can't cleanly merge it, so you can fork that one if you want or just start from master here. Sorry to be neglectful... just finished up my tour of duty on the international space station

**Comment by mriveralee** [comment]
@nebstrebor -- I submitted a [pull-request](https://github.com/nebstrebor/django-shortuuidfield/pull/3) that merges the fixes from the older pull request you provided.

**Comment by benrobster** [comment]
merged, and pypi updated.  Thanks for your help.
